### ISSUE TITLE
Cannot consume scoped service

### ISSUE THREAD

**Issue by lolp1** [LSXPrime/Aegis#2]
Hi there,

Going to put this portion in a spoiler tag since it's unrelated to the issue but wanted to add more to the issue.

<details>
  <summary>Miscellaneous </summary>
A couple things. First is, this is an absolutely fantastic open source project. The code is clean, simple, and documentation is sufficient. It is also a project I would have loved to have existed and found a ~3 years ago when I started selling my own software which had a very specific need to have a license system which supported multiple sessions per license with a heart-beat system.

I ended up writing my own in PHP using Laravel as my server was using Invision Power Services for my store and licensing management system and extended it with a plugin to support multiple sessions per a license and heart-beats. As a .NET dev, this is the project I wanted to make but did not have time.

So, with that said, I am going to contribute to the project and if you have any specific thing you need help with let me know otherwise after some time thinking I will propose changes/features and once on the same page go ahead and add them :). 
</details>

So it seems that the following line is causing me issues when I attempt to build and run the project.

### _StartUp.cs_
```csharp
services.AddHostedService<HeartbeatMonitor>();
```
### _Exception details_
```
Message=Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: Aegis.Server.Services.HeartbeatMonitor': Cannot consume scoped service 'Aegis.Server.Data.ApplicationDbContext' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.)
  Source=Microsoft.Extensions.DependencyInjection
```

The following changes fix this issue for me (changed constructor, added an IServiceScopeFactory field, and changed Monitor method to use the dbcontect from the created scope instead of the injected context.

### _HeartbeatMonitor.cs_
```csharp
private readonly IServiceScopeFactory _scopeFactory;
public HeartbeatMonitor(IServiceScopeFactory scopeFactory) => _scopeFactory = scopeFactory;

    private async void Monitor(object? state)
    {
        using var scope = _scopeFactory.CreateScope();

        var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
        var timeoutThreshold = DateTime.UtcNow.Subtract(_heartbeatTimeout);

        var expiredActivations = await dbContext.Activations
            .Where(a => a.LastHeartbeat < timeoutThreshold)
            .ToListAsync();

        dbContext.Activations.RemoveRange(expiredActivations);
        await dbContext.SaveChangesAsync();
    }
```

I actually changed it to this, but the above is the code I showed here as it keeps your existing code the same and still works, but I just implemented BackgroundService directly and used a PeriodicTimer to allow an async execution and forwarding of cancelation token.

```csharp
public sealed class ScopedHeartbeatBackgroundService(
    IServiceScopeFactory ScopeFactory) : BackgroundService
{
    private readonly TimeSpan _heartbeatTimeout = TimeSpan.FromMinutes(10);

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        using var timer = new PeriodicTimer(_heartbeatTimeout);
        while (await timer.WaitForNextTickAsync(stoppingToken))
        {
            var scope = ScopeFactory.CreateScope();

            var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
            var timeoutThreshold = DateTime.UtcNow.Subtract(_heartbeatTimeout);

            var expiredActivations = await dbContext.Activations
                .Where(a => a.LastHeartbeat < timeoutThreshold)
                .ToListAsync(cancellationToken: stoppingToken);

            dbContext.Activations.RemoveRange(expiredActivations);
            await dbContext.SaveChangesAsync(stoppingToken);
        }
    }
}
```

So I am not sure what I am missing that makes the existing code not work. The test still pass for me, this issue only exist when using an actual local database and running the actual server locally, i.e:
```csharp
        services.AddControllers();
        services.AddDbContext<ApplicationDbContext>(options =>
            options.UseSqlite(configuration.GetConnectionString("DefaultConnection")));
```
Do you not get this issue when running this server locally? If not, any idea why I would and why my 'fix' is needed?

**Comment by Xor-el** [comment]
Hello @lolp1 I would first want to indicate that I am not the maintainer of this library but just offering my 2 cents here.

when you call

```csharp
services.AddHostedService<HeartbeatMonitor>();
````
You are essentially registering the **HeartbeatMonitor** as a hosted service, which internally adds it as a **Singleton** in the DI container.

As we know, it is not advisable to consume a **Scoped** service from a **Singleton** because a **Singleton** service does not operate within a request scope. When a **Singleton** service depends on a **Scoped** service, the **Scoped** service might be disposed of while the **Singleton** still needs it. This occurs because the **Scoped** service has a shorter lifecycle (request or scope) compared to the **Singleton**.

The proper way to handle this is to create a scope within the **Singleton** to retrieve the **Scoped** service, as you have done.

as to why they might not have gotten the error locally, this could be due to the [ValidateScopes](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceprovideroptions.validatescopes?view=net-8.0#microsoft-extensions-dependencyinjection-serviceprovideroptions-validatescopes) property set to false by default in the environment they are running against.

However, do note that the default for the [ValidateScopes](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceprovideroptions.validatescopes?view=net-8.0#microsoft-extensions-dependencyinjection-serviceprovideroptions-validatescopes) property would be changing in [ASP.NET Core 9](https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/9.0/hostbuilder-validation).

**Comment by LSXPrime** [comment]
Thank you both for the detailed feedback and contribution! You're absolutely correct about the issue with injecting a scoped service (ApplicationDbContext) into a singleton service (HeartbeatMonitor).

@Xor-el is right on the money with the explanation of scoped and singleton services. The current implementation indeed creates a potential for the ApplicationDbContext to be disposed of while the HeartbeatMonitor still needs it.

The solution proposed by @lolp1, using IServiceScopeFactory to create a scope and resolve the ApplicationDbContext within the Monitor method, is the correct way to handle this dependency.

**The latest commit addresses this issue with some major issues. HeartbeatMonitor now utilizes IServiceScopeFactory to resolve the ApplicationDbContext within a scope, ensuring correct lifetime management and preventing potential issues, and separated core server library from the sample ASP.NET Core project, still, the Nuget package uploading for Aegis.Server encountered package id reservation issue and I contacted support and waiting for replay, but the sample Aegis.Server.AspNetCore project works fine.**

if no any related errors popup after that, you can close the issue anytime.

**Comment by lolp1** [comment]
> Hello @lolp1 I would first want to indicate that I am not a maintainer of this library but just offering my 2 cents here.
> 
> when you call
> 
> ```csharp
> services.AddHostedService<HeartbeatMonitor>();
> ````
> You are essentially registering the **HeartbeatMonitor** as a hosted service, which internally adds it as a **Singleton** in the DI container.
> 
> As we know, it is not advisable to consume a **Scoped** service from a **Singleton** because a **Singleton** service does not operate within a request scope. When a **Singleton** service depends on a **Scoped** service, the **Scoped** service might be disposed of while the **Singleton** still needs it. This occurs because the **Scoped** service has a shorter lifecycle (request or scope) compared to the **Singleton**.
> 
> The proper way to handle this is to create a scope within the **Singleton** to retrieve the **Scoped** service, as you have done.
> 
> as to why they might not have gotten the error locally, this could be due to the [ValidateScopes](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceprovideroptions.validatescopes?view=net-8.0#microsoft-extensions-dependencyinjection-serviceprovideroptions-validatescopes) property set to false by default in the environment they are running against.
> 
> However, do note that the default for the [ValidateScopes](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceprovideroptions.validatescopes?view=net-8.0#microsoft-extensions-dependencyinjection-serviceprovideroptions-validatescopes) property would be changing in [ASP.NET Core 9](https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/9.0/hostbuilder-validation).

> as to why they might not have gotten the error locally, this could be due to the ValidateScopes property set to false by default in the environment they are running against.

Thanks I was actually unaware of that property. I rarely use hosted service and when I do I use the official reference docs which uses a scope factory instance, which is why I tried that change upon seeing the exception.

**Comment by LSXPrime** [comment]
> still, the Nuget package uploading for Aegis.Server encountered package id reservation issue and I contacted support and waiting for replay

the Nuget package "[Aegis.Server](https://www.nuget.org/packages/Aegis.Server/1.1.0)" issue has been addressed and since this issue got fixed too, I am gonna close it for now
