### ISSUE TITLE
Notice: Aegis.Server NuGet Package Unavailable - Pending ID Reservation

### ISSUE THREAD

**Issue by LSXPrime** [LSXPrime/Aegis#3]
I recently published the [Aegis](https://www.nuget.org/packages/Aegis) licensing library to NuGet. I am now attempting to publish an extension package for server-side functionality called "Aegis.Server". However, I encountered an error during the NuGet upload:

`"The package ID is reserved. You can upload your package with a different package ID. Reach out to support@nuget.org if you have questions."`

This is despite the fact that no package with the ID "Aegis.Server" currently exists on NuGet. I believe this is a logical and appropriate name for the extension, clearly indicating its relationship to the core "Aegis" library.

**Latest Commit Update:**

In the latest commit, I separated the core Aegis.Server library from the sample ASP.NET Core project. Unfortunately, the NuGet package upload for Aegis.Server still encounters the package ID reservation issue. I have contacted NuGet support and am currently proceeding with the package ID reservation process. 

**Workaround:**

The sample Aegis.Server.AspNetCore project, which demonstrates server-side integration, works fine. However, **Aegis.Server is not yet available on NuGet**.  

If you require the server-side functionality, you can temporarily use the Aegis.Server library directly from this repository until the NuGet package issue is resolved.

**Status:**

- Package ID reservation request submitted to NuGet support.
- Awaiting approval for the "Aegis.Server" package ID.

**Comment by LSXAxeller** [comment]
Issue Addressed
"Aegis" prefix has been reserved for us, thanks to Nuget support team.
[Package Aegis.Server uploaded successfully to Nuget](https://www.nuget.org/packages/Aegis.Server/1.1.0)

**Comment by LSXPrime** [comment]
Issue Addressed
"Aegis" prefix has been reserved for us, thanks to Nuget support team.
[Package Aegis.Server uploaded successfully to Nuget](https://www.nuget.org/packages/Aegis.Server/1.1.0)
