### ISSUE TITLE
LoadLicenseAsync() with public key as param

### ISSUE THREAD

**Issue by xmenxwk** [LSXPrime/Aegis#7]
Since public key is being used to verify, so in main method of LoadLicenseAsync() thats doing the verification and loading, it should have public key as parameter and another LoadLicenseAsync() to call it with public key loaded from LicenseUtils. In that way, I can directly call LoadLicenseAsync with public key. And should do same with SaveLicense() with private key as parameter. Right now, everything is dependent on LicenseUtils.LicensingSecrets. It should be optional.

Also, whats the use of LicensingSecrets.EncryptionKey ?

**Comment by LSXPrime** [comment]
I forgot to delete `LicensingSecrets.EncryptionKey` property.

although passing public key as parameter to  `LoadLicenseAsync ` is an option, the internal method `VerifyLicenseData` depends on it too, which will make us passing it a lot of times to finish the validation process, so I find centralizing the access is a better approach, and now you can do it just by

```csharp
var secrets = new LicensingSecrets
{
    PublicKey = "YOUR_PUBLIC_KEY",
    PrivateKey = "YOUR_PRIVATE_KEY_IF_NEEDED",
    ApiKey = "YOUR_SERVER_API_KEY"
};

LicenseUtils.LoadLicensingSecrets(secrets);
```

And passing the private key to `SaveLicense()` is a good option.

**Comment by LSXPrime** [comment]
Since there have been no updates on this issue, I will close it and consider it resolved.

**Comment by FarhadMohseni** [comment]
@LSXPrime The issue is that there's no way to store only the public key in the licensing secrets (Without manually grabbing it and creating a LicensingSecrets Object), nor it's mentioned in the readme, It's a critical security issue, If the private key exists on the client side than everyone can generate licenses by decompiling the app!
