### ISSUE TITLE
Data Converter

### ISSUE THREAD

**Issue by xmenxwk** [LSXPrime/Aegis#9]
Hi, I have one more request, Can you add a license data converter interface then implement json data converter as default. Right now its using
JsonSerializer.SerializeToUtf8Bytes in LicenseManager>SaveLicense() 
JsonSerializer.Deserialize in LicenseValidator>VerifyLicenseData()

It would be better if it could be customizable because I want to use my own converter instead of json.

**Comment by LSXPrime** [comment]
I love seeing feature requests! They give me great ideas for what to include in the next update.

Implementing a converter interface with a default JSON implementation (and the ability to plug in custom converters) is certainly an interesting idea. I'll consider adding it for the next update.

**Comment by xmenxwk** [comment]
Hi,
Any update on this ?

**Comment by LSXPrime** [comment]
I am waiting to receive more feature requests or some more feature ideas before releasing the next update; however, if it's urgent, I will commit an update with this feature sooner.

**Comment by xmenxwk** [comment]
Its not urgent but needed soon.

**Comment by LSXPrime** [comment]
I implemented the `ILicenseSerializer` interface and the `JsonLicenseSerializer` class, allowing for the ability to switch between different serialization formats and implement custom serialization logic.

[Updated README with Custom Serialization reference. ](https://github.com/LSXPrime/Aegis?tab=readme-ov-file#custom-serialization)

I am now closing this issue, but please don't hesitate to ask questions or provide additional information in the replies if needed. If a related issue arises, feel free to re-open this issue at any time.
